# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataLoader.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataLoader.proto',
  package='BSU.DataLoader',
  syntax='proto3',
  serialized_options=b'\252\002\017DataForStudents',
  serialized_pb=b'\n\x10\x64\x61taLoader.proto\x12\x0e\x42SU.DataLoader\"?\n\x0fTaskDataRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x1c\n\x14\x61\x63\x61\x64\x65micDisciplineId\x18\x02 \x01(\t\"1\n\rTaskDataReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x12\n\ndataFormat\x18\x02 \x01(\t2\xb0\x01\n\nDataLoader\x12K\n\tFetchData\x12\x1f.BSU.DataLoader.TaskDataRequest\x1a\x1d.BSU.DataLoader.TaskDataReply\x12U\n\x11\x46\x65tchDataAsStream\x12\x1f.BSU.DataLoader.TaskDataRequest\x1a\x1d.BSU.DataLoader.TaskDataReply0\x01\x42\x12\xaa\x02\x0f\x44\x61taForStudentsb\x06proto3'
)




_TASKDATAREQUEST = _descriptor.Descriptor(
  name='TaskDataRequest',
  full_name='BSU.DataLoader.TaskDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='BSU.DataLoader.TaskDataRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='academicDisciplineId', full_name='BSU.DataLoader.TaskDataRequest.academicDisciplineId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=99,
)


_TASKDATAREPLY = _descriptor.Descriptor(
  name='TaskDataReply',
  full_name='BSU.DataLoader.TaskDataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='BSU.DataLoader.TaskDataReply.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataFormat', full_name='BSU.DataLoader.TaskDataReply.dataFormat', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['TaskDataRequest'] = _TASKDATAREQUEST
DESCRIPTOR.message_types_by_name['TaskDataReply'] = _TASKDATAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskDataRequest = _reflection.GeneratedProtocolMessageType('TaskDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKDATAREQUEST,
  '__module__' : 'dataLoader_pb2'
  # @@protoc_insertion_point(class_scope:BSU.DataLoader.TaskDataRequest)
  })
_sym_db.RegisterMessage(TaskDataRequest)

TaskDataReply = _reflection.GeneratedProtocolMessageType('TaskDataReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKDATAREPLY,
  '__module__' : 'dataLoader_pb2'
  # @@protoc_insertion_point(class_scope:BSU.DataLoader.TaskDataReply)
  })
_sym_db.RegisterMessage(TaskDataReply)


DESCRIPTOR._options = None

_DATALOADER = _descriptor.ServiceDescriptor(
  name='DataLoader',
  full_name='BSU.DataLoader.DataLoader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=153,
  serialized_end=329,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchData',
    full_name='BSU.DataLoader.DataLoader.FetchData',
    index=0,
    containing_service=None,
    input_type=_TASKDATAREQUEST,
    output_type=_TASKDATAREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FetchDataAsStream',
    full_name='BSU.DataLoader.DataLoader.FetchDataAsStream',
    index=1,
    containing_service=None,
    input_type=_TASKDATAREQUEST,
    output_type=_TASKDATAREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATALOADER)

DESCRIPTOR.services_by_name['DataLoader'] = _DATALOADER

# @@protoc_insertion_point(module_scope)
